import { PrismaClient, type DietType, type MealSlot } from "@prisma/client";

const prisma = new PrismaClient();

interface RecipeSeed {
  name: string;
  description: string;
  imageQuery: string;
  kcal: number;
  proteinG: number;
  carbsG: number;
  fatG: number;
  prepTimeMin: number;
  servings: number;
  mealSlots: MealSlot[];
  dietTypes: DietType[];
  allergens: string[];
  ingredients: string[];
  instructions: string[];
  isTrending?: boolean;
  trendSource?: string;
}

const ALL_DIETS: DietType[] = [
  "OMNIVORE",
  "VEGETARIAN",
  "VEGAN",
  "PESCETARIAN",
  "HALAL",
  "KOSHER",
];

const recipes: RecipeSeed[] = [
  // ---- Trending (Social Media) ----
  {
    name: "Koreanischer Gurkensalat (Oi Muchim)",
    description: "Knackiger, scharf-süß-saurer Gurkensalat mit Sesam, Chiliflocken und Knoblauch, der TikTok/Insta-Sommer-Trend 2026.",
    imageQuery: "korean cucumber salad",
    kcal: 180,
    proteinG: 4,
    carbsG: 14,
    fatG: 12,
    prepTimeMin: 10,
    servings: 2,
    mealSlots: ["LUNCH", "SNACK", "DINNER"],
    dietTypes: [...ALL_DIETS, "VEGAN", "KETO", "LOW_CARB", "PALEO"],
    allergens: ["sesam", "soja"],
    ingredients: [
      "2 Salatgurken",
      "1 TL Salz",
      "2 EL Sesamöl",
      "1 EL geröstete Sesamsamen",
      "1-2 TL Chiliflocken (Gochugaru)",
      "2 Knoblauchzehen, fein gehackt",
      "1 EL Reisessig",
      "1 TL Sojasauce",
      "1 Frühlingszwiebel, in Ringen",
    ],
    instructions: [
      "Gurken längs halbieren, in dünne Halbmonde schneiden.",
      "Mit Salz vermengen und 10 Minuten ziehen lassen, dann überschüssiges Wasser abgießen/leicht ausdrücken.",
      "Knoblauch, Sesamöl, Reisessig, Sojasauce und Chiliflocken in einer Schüssel verrühren.",
      "Gurken zur Marinade geben und gut vermengen.",
      "Mit Sesam und Frühlingszwiebel bestreuen, sofort servieren oder 10 Minuten durchziehen lassen.",
    ],
    isTrending: true,
    trendSource: "Instagram Reels / TikTok, Sommer 2026",
  },
  {
    name: "Udon-Salat mit Erdnuss-Dressing",
    description: "Kalte Udon-Nudeln mit knackigem Gemüse und cremigem Erdnuss-Limetten-Dressing, gerade viral auf Social Media.",
    imageQuery: "cold udon noodle salad",
    kcal: 520,
    proteinG: 18,
    carbsG: 72,
    fatG: 16,
    prepTimeMin: 20,
    servings: 2,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["OMNIVORE", "VEGETARIAN", "VEGAN", "PESCETARIAN"],
    allergens: ["gluten", "erdnuss", "soja"],
    ingredients: [
      "200 g Udon-Nudeln (getrocknet oder vorgekocht)",
      "3 EL Erdnussbutter",
      "1 Limette, Saft",
      "2 EL Sojasauce",
      "1 TL Ahornsirup oder Honig",
      "1 Karotte, in feinen Streifen",
      "1/2 Salatgurke, in Streifen",
      "2 Frühlingszwiebeln, in Ringen",
      "1 EL geröstete Erdnüsse, gehackt",
    ],
    instructions: [
      "Udon-Nudeln nach Packungsangabe kochen, abgießen und mit kaltem Wasser abschrecken.",
      "Für das Dressing Erdnussbutter, Limettensaft, Sojasauce und Ahornsirup glattrühren (bei Bedarf mit 1-2 EL warmem Wasser verdünnen).",
      "Karotte und Gurke in feine Streifen hobeln oder raspeln.",
      "Nudeln mit dem Dressing vermengen, Gemüse untermischen.",
      "Mit Frühlingszwiebeln und gehackten Erdnüssen bestreuen und kalt servieren.",
    ],
    isTrending: true,
    trendSource: "TikTok/Insta-Trend 2026",
  },
  {
    name: "Cottage-Cheese-Bowl mit Honig & Beeren",
    description: "High-Protein-Frühstück im 'Cottage Cheese'-Trend: cremiger Hüttenkäse mit Beeren, Honig und Granola.",
    imageQuery: "cottage cheese bowl berries",
    kcal: 380,
    proteinG: 32,
    carbsG: 38,
    fatG: 11,
    prepTimeMin: 5,
    servings: 1,
    mealSlots: ["BREAKFAST", "SNACK", "POST_WORKOUT"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch", "gluten", "nüsse"],
    ingredients: [
      "200 g Hüttenkäse",
      "1 EL Honig",
      "80 g Heidelbeeren",
      "80 g Erdbeeren, geviertelt",
      "3 EL Granola",
      "1 Prise Zimt",
    ],
    instructions: [
      "Hüttenkäse in eine Schale geben.",
      "Beeren waschen und darüber verteilen.",
      "Mit Honig beträufeln und mit Zimt bestäuben.",
      "Granola erst kurz vor dem Essen darüberstreuen, damit es knusprig bleibt.",
    ],
    isTrending: true,
    trendSource: "Instagram/TikTok High-Protein-Trend 2026",
  },
  {
    name: "Baked Feta Pasta",
    description: "Ofen-Feta mit Kirschtomaten, Olivenöl und Kräutern, geschmolzen über Pasta. Ein Social-Media-Dauerbrenner.",
    imageQuery: "baked feta pasta",
    kcal: 640,
    proteinG: 22,
    carbsG: 78,
    fatG: 24,
    prepTimeMin: 35,
    servings: 2,
    mealSlots: ["DINNER", "LUNCH"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["gluten", "milch"],
    ingredients: [
      "200 g Feta (am Stück)",
      "400 g Kirschtomaten",
      "4 EL Olivenöl",
      "3 Knoblauchzehen",
      "1 TL getrockneter Oregano",
      "250 g Pasta",
      "1 Handvoll Basilikum",
      "Salz, Pfeffer",
    ],
    instructions: [
      "Ofen auf 200°C Ober-/Unterhitze vorheizen.",
      "Kirschtomaten, ganze Knoblauchzehen und den Feta-Block in eine Auflaufform geben, mit Olivenöl beträufeln, mit Oregano, Salz und Pfeffer würzen.",
      "20-25 Minuten backen, bis die Tomaten aufplatzen und der Feta goldbraun ist.",
      "In der Zwischenzeit die Pasta nach Packungsangabe in Salzwasser kochen, etwas Nudelwasser aufheben, abgießen.",
      "Feta und Tomaten mit einer Gabel zu einer cremigen Sauce zerdrücken, Knoblauch mit einarbeiten.",
      "Pasta unterheben, bei Bedarf mit Nudelwasser verdünnen. Mit frischem Basilikum servieren.",
    ],
    isTrending: true,
    trendSource: "TikTok-Rezept, seit 2021 wiederkehrender Trend",
  },
  {
    name: "Protein-Chia-Pudding Vanille",
    description: "Chiasamen in Proteinmilch mit Vanille eingeweicht, einfaches High-Protein-Meal-Prep aus den Reels.",
    imageQuery: "protein chia pudding",
    kcal: 320,
    proteinG: 28,
    carbsG: 24,
    fatG: 12,
    prepTimeMin: 5,
    servings: 1,
    mealSlots: ["BREAKFAST", "SNACK"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch"],
    ingredients: [
      "4 EL Chiasamen",
      "1 Messlöffel Vanille-Proteinpulver",
      "250 ml Milch (oder Pflanzendrink)",
      "1/2 TL Vanilleextrakt",
      "1 TL Ahornsirup",
    ],
    instructions: [
      "Proteinpulver mit Milch in einem Glas glattrühren (Schneebesen oder Shaker).",
      "Chiasamen, Vanilleextrakt und Ahornsirup einrühren.",
      "Abdecken und mindestens 3 Stunden, am besten über Nacht, im Kühlschrank quellen lassen.",
      "Vor dem Servieren nochmal umrühren, damit sich keine Klumpen bilden.",
    ],
    isTrending: true,
    trendSource: "Instagram Meal-Prep-Reels 2026",
  },
  {
    name: "Rice Paper Dumplings (Knusprige Reispapier-Taschen)",
    description: "Mit Gemüse und Glasnudeln gefüllte, in der Pfanne knusprig gebratene Reispapier-Dumplings, viraler Snack-Trend.",
    imageQuery: "rice paper dumplings",
    kcal: 410,
    proteinG: 14,
    carbsG: 58,
    fatG: 14,
    prepTimeMin: 30,
    servings: 2,
    mealSlots: ["LUNCH", "DINNER", "SNACK"],
    dietTypes: ["OMNIVORE", "VEGETARIAN", "VEGAN", "PESCETARIAN"],
    allergens: ["soja"],
    ingredients: [
      "8 Blatt Reispapier",
      "50 g Glasnudeln",
      "1 Karotte, geraspelt",
      "1/4 Kohl, fein geschnitten",
      "2 EL Sojasauce",
      "1 TL geriebener Ingwer",
      "2 EL neutrales Öl zum Braten",
    ],
    instructions: [
      "Glasnudeln nach Packungsangabe einweichen, abtropfen und grob schneiden.",
      "Mit Karotte, Kohl, Sojasauce und Ingwer vermengen.",
      "Reispapier kurz in warmem Wasser anfeuchten, Füllung mittig platzieren und wie ein Päckchen einschlagen.",
      "In einer Pfanne mit Öl bei mittlerer Hitze von beiden Seiten 2-3 Minuten knusprig goldbraun braten.",
      "Mit Sojasauce oder Chilisauce zum Dippen servieren.",
    ],
    isTrending: true,
    trendSource: "TikTok-Trend 2023-2026",
  },

  // ---- Frühstück ----
  {
    name: "Griechisches Joghurt-Porridge",
    description: "Haferflocken mit griechischem Joghurt, Nüssen und frischem Obst.",
    imageQuery: "greek yogurt oat porridge",
    kcal: 420,
    proteinG: 26,
    carbsG: 52,
    fatG: 12,
    prepTimeMin: 8,
    servings: 1,
    mealSlots: ["BREAKFAST"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch", "gluten", "nüsse"],
    ingredients: [
      "60 g Haferflocken",
      "150 ml Milch oder Wasser",
      "150 g griechischer Joghurt",
      "1 Banane, in Scheiben",
      "20 g Walnüsse, gehackt",
      "1 TL Honig",
    ],
    instructions: [
      "Haferflocken mit Milch/Wasser in einem Topf aufkochen und 3-4 Minuten unter Rühren köcheln lassen, bis sie cremig sind.",
      "Etwas abkühlen lassen, dann griechischen Joghurt unterrühren.",
      "In eine Schale füllen, mit Bananenscheiben und Walnüssen toppen.",
      "Mit Honig beträufeln und servieren.",
    ],
  },
  {
    name: "Rührei mit Vollkorntoast und Avocado",
    description: "Klassisches proteinreiches Frühstück mit gesunden Fetten aus der Avocado.",
    imageQuery: "scrambled eggs avocado toast",
    kcal: 480,
    proteinG: 24,
    carbsG: 34,
    fatG: 26,
    prepTimeMin: 12,
    servings: 1,
    mealSlots: ["BREAKFAST"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["ei", "gluten"],
    ingredients: [
      "3 Eier",
      "2 Scheiben Vollkornbrot",
      "1/2 Avocado",
      "1 TL Butter",
      "Salz, Pfeffer",
    ],
    instructions: [
      "Eier in einer Schüssel verquirlen, mit Salz und Pfeffer würzen.",
      "Butter in einer Pfanne bei niedriger bis mittlerer Hitze schmelzen.",
      "Eier hineingeben und unter gelegentlichem Rühren langsam stocken lassen (nicht zu heiß, sonst werden sie trocken).",
      "Währenddessen das Vollkornbrot toasten und die Avocado zerdrücken oder in Scheiben schneiden.",
      "Toast mit Avocado bestreichen, Rührei daneben oder darauf anrichten, nachwürzen.",
    ],
  },
  {
    name: "Tofu-Scramble mit Gemüse",
    description: "Veganes Rührei-Pendant aus Tofu mit Paprika, Zwiebel und Kurkuma.",
    imageQuery: "tofu scramble vegetables",
    kcal: 340,
    proteinG: 22,
    carbsG: 20,
    fatG: 18,
    prepTimeMin: 15,
    servings: 1,
    mealSlots: ["BREAKFAST"],
    dietTypes: ["VEGAN", "VEGETARIAN", "OMNIVORE"],
    allergens: ["soja"],
    ingredients: [
      "200 g fester Tofu",
      "1/2 Paprika, gewürfelt",
      "1/2 Zwiebel, gewürfelt",
      "1/2 TL Kurkuma",
      "1 EL Olivenöl",
      "Salz, Pfeffer",
    ],
    instructions: [
      "Tofu mit einer Gabel grob zerbröseln (so entsteht die Rührei-Optik).",
      "Zwiebel und Paprika in Olivenöl bei mittlerer Hitze 3-4 Minuten andünsten.",
      "Tofu-Bröckel dazugeben, mit Kurkuma, Salz und Pfeffer würzen.",
      "5-7 Minuten unter gelegentlichem Wenden braten, bis alles heiß und leicht goldbraun ist.",
    ],
  },
  {
    name: "Skyr-Bowl mit Nüssen und Datteln",
    description: "Proteinreicher Skyr mit karamelligen Datteln und knackigen Nüssen.",
    imageQuery: "skyr bowl dates nuts",
    kcal: 360,
    proteinG: 30,
    carbsG: 34,
    fatG: 10,
    prepTimeMin: 5,
    servings: 1,
    mealSlots: ["BREAKFAST", "SNACK", "POST_WORKOUT"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch", "nüsse"],
    ingredients: [
      "250 g Skyr",
      "3 Datteln, entsteint und gehackt",
      "20 g Mandeln, gehackt",
      "1 Prise Zimt",
    ],
    instructions: [
      "Skyr in eine Schale geben.",
      "Datteln und Mandeln grob hacken.",
      "Über den Skyr verteilen und mit Zimt bestäuben.",
    ],
  },

  // ---- Mittag / Abend ----
  {
    name: "Hähnchen-Bowl mit Quinoa und Gemüse",
    description: "Gegrilltes Hähnchen, Quinoa, geröstetes Gemüse und Tahini-Dressing.",
    imageQuery: "chicken quinoa bowl",
    kcal: 620,
    proteinG: 48,
    carbsG: 58,
    fatG: 20,
    prepTimeMin: 30,
    servings: 1,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["OMNIVORE", "HALAL", "KOSHER"],
    allergens: ["sesam"],
    ingredients: [
      "180 g Hähnchenbrust",
      "70 g Quinoa (trocken)",
      "150 g Brokkoli, in Röschen",
      "1/2 Paprika, in Streifen",
      "2 EL Tahini",
      "1/2 Zitrone, Saft",
      "1 EL Olivenöl",
      "Salz, Pfeffer",
    ],
    instructions: [
      "Quinoa nach Packungsangabe in Salzwasser kochen (ca. 15 Minuten), abgießen und ausdampfen lassen.",
      "Ofen auf 200°C vorheizen. Brokkoli und Paprika mit Olivenöl, Salz und Pfeffer vermengen, 15-18 Minuten rösten.",
      "Hähnchenbrust würzen und in einer Pfanne 5-6 Minuten pro Seite goldbraun braten, bis der Kern durch ist.",
      "Tahini mit Zitronensaft und etwas Wasser zu einem cremigen Dressing verrühren.",
      "Quinoa, Gemüse und in Streifen geschnittenes Hähnchen in einer Bowl anrichten, mit Dressing beträufeln.",
    ],
  },
  {
    name: "Lachs mit Süßkartoffel und Spinat",
    description: "Ofenlachs mit gebackener Süßkartoffel und sautiertem Spinat, ideal für Ausdauersportler.",
    imageQuery: "salmon sweet potato spinach",
    kcal: 580,
    proteinG: 42,
    carbsG: 46,
    fatG: 24,
    prepTimeMin: 35,
    servings: 1,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["OMNIVORE", "PESCETARIAN"],
    allergens: ["fisch"],
    ingredients: [
      "180 g Lachsfilet",
      "1 mittelgroße Süßkartoffel",
      "150 g Blattspinat",
      "1 EL Olivenöl",
      "1 Knoblauchzehe",
      "Salz, Pfeffer, Zitrone",
    ],
    instructions: [
      "Ofen auf 200°C vorheizen. Süßkartoffel in Spalten schneiden, mit etwas Öl, Salz und Pfeffer mischen, 25-30 Minuten backen.",
      "Lachsfilet salzen und pfeffern, nach 15 Minuten Backzeit der Süßkartoffel mit auf das Blech legen und 12-15 Minuten mitbacken.",
      "Kurz vor Ende Knoblauch in einer Pfanne mit Olivenöl andünsten, Spinat zugeben und zusammenfallen lassen.",
      "Alles zusammen anrichten, mit Zitronensaft beträufeln.",
    ],
  },
  {
    name: "Linsen-Curry mit Reis",
    description: "Cremiges rotes Linsencurry mit Kokosmilch, serviert mit Basmatireis.",
    imageQuery: "red lentil curry rice",
    kcal: 560,
    proteinG: 22,
    carbsG: 82,
    fatG: 16,
    prepTimeMin: 30,
    servings: 2,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["VEGAN", "VEGETARIAN", "OMNIVORE", "HALAL", "KOSHER"],
    allergens: [],
    ingredients: [
      "200 g rote Linsen",
      "200 ml Kokosmilch",
      "150 g Basmatireis",
      "1 Zwiebel, gewürfelt",
      "2 TL Currypulver",
      "1 TL geriebener Ingwer",
      "2 Knoblauchzehen",
      "400 ml Gemüsebrühe",
    ],
    instructions: [
      "Reis nach Packungsangabe kochen.",
      "Zwiebel, Knoblauch und Ingwer in einem Topf mit etwas Öl 3-4 Minuten andünsten, Currypulver kurz mitrösten.",
      "Linsen zugeben, mit Gemüsebrühe ablöschen und 15 Minuten köcheln lassen, bis die Linsen weich sind.",
      "Kokosmilch einrühren, weitere 5 Minuten köcheln lassen, mit Salz abschmecken.",
      "Mit Reis servieren.",
    ],
  },
  {
    name: "Steak mit grünem Spargel",
    description: "Rumpsteak mit grünem Spargel und Kräuterbutter, klassisches Low-Carb-Powerlifting-Dinner.",
    imageQuery: "steak green asparagus",
    kcal: 650,
    proteinG: 55,
    carbsG: 12,
    fatG: 42,
    prepTimeMin: 25,
    servings: 1,
    mealSlots: ["DINNER"],
    dietTypes: ["OMNIVORE", "KETO", "LOW_CARB", "PALEO"],
    allergens: ["milch"],
    ingredients: [
      "200 g Rumpsteak",
      "200 g grüner Spargel",
      "2 EL Butter",
      "1 Knoblauchzehe",
      "1 EL Petersilie, gehackt",
      "Salz, Pfeffer",
    ],
    instructions: [
      "Steak 20 Minuten vor dem Braten aus dem Kühlschrank nehmen, damit es Zimmertemperatur hat.",
      "Spargel am unteren Ende schälen, in einer Pfanne mit etwas Butter 6-8 Minuten braten, salzen.",
      "Eine zweite Pfanne stark erhitzen, Steak kräftig salzen und pfeffern, 2-3 Minuten pro Seite scharf anbraten (je nach gewünschtem Gargrad).",
      "Butter, Knoblauch und Petersilie in die Pfanne geben, Steak damit übergießen (Basten).",
      "Steak 5 Minuten ruhen lassen, dann in Scheiben schneiden und mit dem Spargel servieren.",
    ],
  },
  {
    name: "Falafel-Teller mit Hummus und Fladenbrot",
    description: "Knusprige Falafel mit cremigem Hummus, Salat und warmem Fladenbrot.",
    imageQuery: "falafel plate hummus",
    kcal: 610,
    proteinG: 20,
    carbsG: 78,
    fatG: 22,
    prepTimeMin: 30,
    servings: 2,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["VEGAN", "VEGETARIAN", "OMNIVORE", "HALAL", "KOSHER"],
    allergens: ["gluten", "sesam"],
    ingredients: [
      "250 g Kichererbsen (aus der Dose, abgetropft, oder vorgekocht)",
      "200 g Hummus",
      "2 Fladenbrote",
      "1 Handvoll Salat",
      "1 Tomate, gewürfelt",
      "2 EL Tahini",
      "Öl zum Braten",
    ],
    instructions: [
      "Kichererbsen mit Gewürzen (Kreuzkümmel, Knoblauch, Salz) im Mixer grob pürieren, zu kleinen Bällchen formen.",
      "Falafel in einer Pfanne mit ausreichend Öl rundum goldbraun braten, ca. 6-8 Minuten.",
      "Fladenbrote kurz in einer trockenen Pfanne oder im Ofen aufwärmen.",
      "Hummus auf den Tellern verteilen, Falafel, Salat und Tomate daneben anrichten.",
      "Mit Tahini beträufeln und mit Fladenbrot servieren.",
    ],
  },
  {
    name: "Garnelen-Pad-Thai",
    description: "Gebratene Reisnudeln mit Garnelen, Ei, Erdnüssen und Limette.",
    imageQuery: "shrimp pad thai",
    kcal: 590,
    proteinG: 34,
    carbsG: 66,
    fatG: 18,
    prepTimeMin: 25,
    servings: 2,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["OMNIVORE", "PESCETARIAN"],
    allergens: ["schalentiere", "ei", "erdnuss", "soja"],
    ingredients: [
      "200 g Reisnudeln",
      "250 g Garnelen, geschält",
      "2 Eier",
      "3 EL Sojasauce",
      "1 EL Limettensaft",
      "3 EL geröstete Erdnüsse, gehackt",
      "2 Frühlingszwiebeln",
      "2 EL Öl",
    ],
    instructions: [
      "Reisnudeln nach Packungsangabe einweichen/kochen, abgießen.",
      "Öl in einem Wok stark erhitzen, Garnelen 2-3 Minuten anbraten, bis sie rosa sind, herausnehmen.",
      "Eier in den Wok geben, kurz verrühren bis sie stocken, dann Nudeln zugeben.",
      "Sojasauce und Limettensaft zugeben, alles gut durchschwenken.",
      "Garnelen zurück in den Wok geben, mit Erdnüssen und Frühlingszwiebeln bestreuen, kurz erhitzen und servieren.",
    ],
  },
  {
    name: "Gemüse-Chili sin Carne",
    description: "Herzhaftes Chili mit schwarzen Bohnen, Mais und Paprika.",
    imageQuery: "vegetarian chili beans",
    kcal: 480,
    proteinG: 24,
    carbsG: 66,
    fatG: 12,
    prepTimeMin: 30,
    servings: 2,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["VEGAN", "VEGETARIAN", "OMNIVORE", "HALAL", "KOSHER"],
    allergens: [],
    ingredients: [
      "1 Dose schwarze Bohnen, abgetropft",
      "1 Dose Kidneybohnen, abgetropft",
      "200 g Mais (Dose oder TK)",
      "1 Paprika, gewürfelt",
      "1 Dose gehackte Tomaten",
      "1 Zwiebel, gewürfelt",
      "1 EL Chilipulver",
      "1 TL Kreuzkümmel",
    ],
    instructions: [
      "Zwiebel und Paprika in einem großen Topf mit etwas Öl 4-5 Minuten andünsten.",
      "Chilipulver und Kreuzkümmel kurz mitrösten, bis es duftet.",
      "Tomaten, Bohnen und Mais zugeben, gut umrühren.",
      "20 Minuten bei mittlerer Hitze köcheln lassen, gelegentlich umrühren.",
      "Mit Salz und Pfeffer abschmecken, optional mit Reis servieren.",
    ],
  },
  {
    name: "Putengeschnetzeltes mit Vollkornreis",
    description: "Mageres Putenfleisch in Champignon-Sauce mit Vollkornreis.",
    imageQuery: "turkey stew rice",
    kcal: 540,
    proteinG: 46,
    carbsG: 54,
    fatG: 14,
    prepTimeMin: 25,
    servings: 1,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["OMNIVORE", "HALAL"],
    allergens: ["milch"],
    ingredients: [
      "200 g Putenbrust, in Streifen",
      "150 g Champignons, in Scheiben",
      "70 g Vollkornreis (trocken)",
      "1/2 Zwiebel, gewürfelt",
      "100 ml Sahne (oder Sahnealternative)",
      "1 EL Öl",
      "Salz, Pfeffer",
    ],
    instructions: [
      "Reis nach Packungsangabe kochen.",
      "Putenstreifen in Öl bei starker Hitze 3-4 Minuten scharf anbraten, herausnehmen.",
      "Zwiebel und Champignons in derselben Pfanne 4-5 Minuten andünsten.",
      "Sahne zugeben, kurz einkochen lassen, Puten zurück in die Pfanne geben.",
      "Mit Salz und Pfeffer abschmecken, mit dem Reis servieren.",
    ],
  },

  // ---- Snacks / Zwischenmahlzeiten ----
  {
    name: "Protein-Shake Banane-Erdnuss",
    description: "Schneller Shake aus Proteinpulver, Banane und Erdnussbutter.",
    imageQuery: "protein shake banana",
    kcal: 320,
    proteinG: 34,
    carbsG: 28,
    fatG: 9,
    prepTimeMin: 5,
    servings: 1,
    mealSlots: ["SNACK", "POST_WORKOUT"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch", "erdnuss"],
    ingredients: [
      "1 Messlöffel Proteinpulver",
      "1 Banane",
      "1 EL Erdnussbutter",
      "250 ml Milch",
      "einige Eiswürfel",
    ],
    instructions: [
      "Alle Zutaten in einen Mixer geben.",
      "30-45 Sekunden auf hoher Stufe mixen, bis die Konsistenz glatt und cremig ist.",
      "Sofort servieren.",
    ],
  },
  {
    name: "Hüttenkäse mit Ananas",
    description: "Erfrischender proteinreicher Snack, ideal als Late-Night-Option.",
    imageQuery: "cottage cheese pineapple",
    kcal: 220,
    proteinG: 24,
    carbsG: 18,
    fatG: 5,
    prepTimeMin: 3,
    servings: 1,
    mealSlots: ["SNACK"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch"],
    ingredients: ["200 g Hüttenkäse", "100 g Ananas, gewürfelt (frisch oder aus der Dose)"],
    instructions: [
      "Hüttenkäse in eine Schale geben.",
      "Ananasstücke darüber verteilen und servieren.",
    ],
  },
  {
    name: "Studentenfutter-Mix",
    description: "Nüsse, Kerne und Trockenfrüchte für unterwegs.",
    imageQuery: "trail mix nuts",
    kcal: 280,
    proteinG: 9,
    carbsG: 20,
    fatG: 19,
    prepTimeMin: 1,
    servings: 1,
    mealSlots: ["SNACK"],
    dietTypes: ["VEGAN", "VEGETARIAN", "OMNIVORE", "HALAL", "KOSHER", "KETO", "PALEO"],
    allergens: ["nüsse"],
    ingredients: [
      "15 g Mandeln",
      "15 g Walnüsse",
      "15 g Cranberries, getrocknet",
      "15 g Kürbiskerne",
    ],
    instructions: ["Alle Zutaten in einer kleinen Dose oder Tüte mischen — fertig für unterwegs."],
  },
  {
    name: "Reiswaffeln mit Frischkäse und Gurke",
    description: "Leichter, kohlenhydratbetonter Snack für vor dem Training.",
    imageQuery: "rice cakes cream cheese cucumber",
    kcal: 210,
    proteinG: 8,
    carbsG: 30,
    fatG: 6,
    prepTimeMin: 5,
    servings: 1,
    mealSlots: ["SNACK", "PRE_WORKOUT"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch"],
    ingredients: ["3 Reiswaffeln", "3 EL Frischkäse", "1/4 Salatgurke, in Scheiben"],
    instructions: [
      "Reiswaffeln mit Frischkäse bestreichen.",
      "Mit Gurkenscheiben belegen und sofort servieren (sonst werden die Waffeln weich).",
    ],
  },

  // ---- Pre-/Post-Workout ----
  {
    name: "Banane mit Honig",
    description: "Schnell verfügbare Kohlenhydrate, fettarm, ideal kurz vor dem Training.",
    imageQuery: "banana honey",
    kcal: 150,
    proteinG: 2,
    carbsG: 35,
    fatG: 1,
    prepTimeMin: 1,
    servings: 1,
    mealSlots: ["PRE_WORKOUT"],
    dietTypes: ["OMNIVORE", "VEGETARIAN", "VEGAN", "PESCETARIAN", "HALAL", "KOSHER", "PALEO"],
    allergens: [],
    ingredients: ["1 Banane", "1 TL Honig"],
    instructions: ["Banane schälen, längs halbieren und mit Honig beträufeln."],
  },
  {
    name: "Weißbrot-Toast mit Marmelade",
    description: "Leicht verdauliche Carb-Quelle für das Pre-Workout-Fenster.",
    imageQuery: "white toast jam",
    kcal: 220,
    proteinG: 5,
    carbsG: 44,
    fatG: 2,
    prepTimeMin: 3,
    servings: 1,
    mealSlots: ["PRE_WORKOUT"],
    dietTypes: ["OMNIVORE", "VEGETARIAN", "VEGAN"],
    allergens: ["gluten"],
    ingredients: ["2 Scheiben Weißbrot", "2 EL Marmelade"],
    instructions: ["Brot toasten (optional) und mit Marmelade bestreichen."],
  },
  {
    name: "Reiswaffeln mit Honig",
    description: "Fettarmer, schnell verdaulicher Energie-Kick vor dem Sport.",
    imageQuery: "rice cakes honey",
    kcal: 160,
    proteinG: 2,
    carbsG: 36,
    fatG: 1,
    prepTimeMin: 1,
    servings: 1,
    mealSlots: ["PRE_WORKOUT"],
    dietTypes: ["VEGAN", "VEGETARIAN", "OMNIVORE", "HALAL", "KOSHER"],
    allergens: [],
    ingredients: ["3 Reiswaffeln", "2 TL Honig"],
    instructions: ["Reiswaffeln mit Honig bestreichen und servieren."],
  },
  {
    name: "Whey-Shake mit Wasser und Banane",
    description: "Schnell resorbierbares Protein direkt nach dem Training.",
    imageQuery: "whey protein shake",
    kcal: 260,
    proteinG: 36,
    carbsG: 24,
    fatG: 3,
    prepTimeMin: 3,
    servings: 1,
    mealSlots: ["POST_WORKOUT"],
    dietTypes: ["OMNIVORE", "VEGETARIAN"],
    allergens: ["milch"],
    ingredients: ["1 Messlöffel Whey Protein", "300 ml Wasser", "1 Banane"],
    instructions: [
      "Whey Protein, Wasser und Banane in einen Shaker oder Mixer geben.",
      "Kräftig schütteln oder mixen, bis alles gleichmäßig vermischt ist.",
    ],
  },
  {
    name: "Hähnchen-Reis-Bowl (Post-Workout)",
    description: "Klassische Bodybuilding-Kombination aus magerem Hähnchen und weißem Reis.",
    imageQuery: "chicken white rice bowl",
    kcal: 480,
    proteinG: 45,
    carbsG: 60,
    fatG: 8,
    prepTimeMin: 20,
    servings: 1,
    mealSlots: ["POST_WORKOUT", "LUNCH", "DINNER"],
    dietTypes: ["OMNIVORE", "HALAL", "KOSHER"],
    allergens: [],
    ingredients: [
      "180 g Hähnchenbrust",
      "80 g weißer Reis (trocken)",
      "1 EL Sojasauce",
      "1 Frühlingszwiebel, in Ringen",
    ],
    instructions: [
      "Reis nach Packungsangabe kochen.",
      "Hähnchenbrust würzen und in einer Pfanne 5-6 Minuten pro Seite durchbraten.",
      "In Scheiben schneiden, auf den Reis legen, mit Sojasauce beträufeln und mit Frühlingszwiebel bestreuen.",
    ],
  },
  {
    name: "Veganer Post-Workout-Shake",
    description: "Pflanzliches Proteinpulver mit Hafermilch und Beeren.",
    imageQuery: "vegan protein shake berries",
    kcal: 280,
    proteinG: 30,
    carbsG: 30,
    fatG: 5,
    prepTimeMin: 3,
    servings: 1,
    mealSlots: ["POST_WORKOUT"],
    dietTypes: ["VEGAN", "VEGETARIAN", "OMNIVORE"],
    allergens: [],
    ingredients: ["1 Messlöffel veganes Proteinpulver", "300 ml Hafermilch", "100 g gemischte Beeren"],
    instructions: [
      "Alle Zutaten in einen Mixer geben.",
      "30-45 Sekunden mixen, bis die Beeren vollständig püriert sind, dann servieren.",
    ],
  },

  // ---- Keto / Low-Carb ----
  {
    name: "Zucchini-Nudeln mit Pesto und Hähnchen",
    description: "Low-Carb-Alternative zu Pasta mit selbstgemachtem Pesto.",
    imageQuery: "zucchini noodles pesto chicken",
    kcal: 460,
    proteinG: 38,
    carbsG: 12,
    fatG: 28,
    prepTimeMin: 20,
    servings: 1,
    mealSlots: ["LUNCH", "DINNER"],
    dietTypes: ["OMNIVORE", "KETO", "LOW_CARB"],
    allergens: ["nüsse", "milch"],
    ingredients: [
      "2 Zucchini, spiralisiert (Zoodles)",
      "180 g Hähnchenbrust",
      "3 EL Pesto",
      "2 EL Parmesan, gerieben",
      "1 EL Pinienkerne",
      "1 EL Olivenöl",
    ],
    instructions: [
      "Zucchini mit einem Spiralschneider oder Sparschäler zu Nudeln verarbeiten.",
      "Hähnchenbrust würzen und in Olivenöl 5-6 Minuten pro Seite durchbraten, dann in Streifen schneiden.",
      "Zoodles kurz (1-2 Minuten) in derselben Pfanne andünsten, damit sie nicht wässrig werden.",
      "Pesto unterheben, Hähnchen daraufgeben.",
      "Mit Parmesan und Pinienkernen bestreuen und servieren.",
    ],
  },
  {
    name: "Omelett mit Speck und Käse",
    description: "Klassisches Keto-Frühstück mit viel Fett und Protein, wenig Carbs.",
    imageQuery: "bacon cheese omelette",
    kcal: 520,
    proteinG: 32,
    carbsG: 4,
    fatG: 42,
    prepTimeMin: 15,
    servings: 1,
    mealSlots: ["BREAKFAST"],
    dietTypes: ["OMNIVORE", "KETO", "LOW_CARB"],
    allergens: ["ei", "milch"],
    ingredients: [
      "3 Eier",
      "50 g Speckwürfel",
      "40 g geriebener Käse",
      "1 TL Butter",
      "Salz, Pfeffer",
    ],
    instructions: [
      "Speckwürfel in einer Pfanne ohne zusätzliches Fett knusprig auslassen, herausnehmen.",
      "Eier verquirlen, salzen und pfeffern.",
      "Butter in der Pfanne schmelzen, Eier hineingeben und bei mittlerer Hitze am Rand stocken lassen.",
      "Speck und Käse auf eine Hälfte geben, sobald das Omelett fast gestockt ist.",
      "Omelett zusammenklappen, kurz weiterbraten bis der Käse schmilzt, servieren.",
    ],
  },
];

/** Leitet sinnvolle Filter-Tags aus den Rezepteigenschaften ab, statt sie erfinden zu müssen. */
function deriveTags(r: RecipeSeed): string[] {
  const tags: string[] = [];
  if (r.dietTypes.includes("VEGAN")) tags.push("vegan");
  else if (r.dietTypes.includes("VEGETARIAN")) tags.push("vegetarisch");
  if (r.dietTypes.includes("KETO")) tags.push("keto");
  if (r.dietTypes.includes("LOW_CARB")) tags.push("low-carb");
  if (r.prepTimeMin <= 10) tags.push("schnell");
  if (r.proteinG * 4 >= r.kcal * 0.3) tags.push("high-protein");
  if (r.mealSlots.includes("PRE_WORKOUT") || r.mealSlots.includes("POST_WORKOUT")) {
    tags.push("workout");
  }
  if (r.mealSlots.includes("SNACK")) tags.push("snack");
  if (r.isTrending) tags.push("social-media-trend");
  return tags;
}

async function main() {
  console.log(`Seede ${recipes.length} Rezepte...`);
  for (const r of recipes) {
    await prisma.recipe.create({
      data: {
        name: r.name,
        description: r.description,
        imageQuery: r.imageQuery,
        kcal: r.kcal,
        proteinG: r.proteinG,
        carbsG: r.carbsG,
        fatG: r.fatG,
        prepTimeMin: r.prepTimeMin,
        servings: r.servings,
        mealSlots: JSON.stringify(r.mealSlots),
        dietTypes: JSON.stringify(r.dietTypes),
        allergens: JSON.stringify(r.allergens),
        ingredients: JSON.stringify(r.ingredients),
        instructions: JSON.stringify(r.instructions),
        tags: JSON.stringify(deriveTags(r)),
        isTrending: r.isTrending ?? false,
        trendSource: r.trendSource ?? null,
        trendAddedAt: r.isTrending ? new Date() : null,
      },
    });
  }
  console.log("Fertig.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
